use_frameworks!

platform :ios, '8.0'

target 'DDFavouritesUI_Example' do
  pod 'DDFavouritesUI', :path => '../'

  target 'DDFavouritesUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
