#use_frameworks!

platform :ios, '10.0'

load 'modules.rb'

target 'DynamicDelivery' do
  
  module_pods
  
  #Third Party Libraries
  pod 'Reachability'
  pod 'SVProgressHUD', '2.2.5'
  pod 'DeepLinkKit'
  pod 'SDWebImage', '~> 5.1.0'
  pod 'LSAnimator', '2.1.4'
  pod 'IQKeyboardManager'
  pod 'Appboy-iOS-SDK'
  pod 'MRCircularProgressView'
  pod 'Branch', '~> 0.30.0'
  pod 'FBSDKCoreKit', '5.8.0'
  pod 'FBSDKLoginKit', '5.8.0'
  pod 'FBSDKShareKit', '5.8.0'
  pod 'lottie-ios', '2.5.3'
  #  pod 'NewRelicAgent'

  
end
