use_frameworks!

platform :ios, '8.0'

target 'DDOutletsUI_Example' do
  pod 'DDOutletsUI', :path => '../'

  target 'DDOutletsUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
