use_frameworks!

platform :ios, '8.0'

target 'DDFavourites_Example' do
  pod 'DDFavourites', :path => '../'

  target 'DDFavourites_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
