use_frameworks!

platform :ios, '8.0'

target 'DDRedemptionsUI_Example' do
  pod 'DDRedemptionsUI', :path => '../'

  target 'DDRedemptionsUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
