use_frameworks!

platform :ios, '8.0'

target 'DDLocationsUI_Example' do
  pod 'DDLocationsUI', :path => '../'

  target 'DDLocationsUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
