use_frameworks!

platform :ios, '8.0'

target 'DDLocations_Example' do
  pod 'DDLocations', :path => '../'

  target 'DDLocations_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
